sample:		sample.cpp render_texture.cpp
		g++ --std=c++17 -framework OpenGL -framework GLUT sample.cpp -o sample -Wno-deprecated


testrender:		test_render.cpp
		g++ --std=c++17 -framework OpenGL -framework GLUT test_render.cpp -o test_render -Wno-deprecated
